export default [
    {
        name: "Movie Watchlist",
        desc: "Discover and save your favorite films effortlessly. Explore movie details and build your personalized watchlist with ease.",
        pic: "../images/projects/MovieWatchlist.png",
        link: "https://luxury-stroopwafel-474f55.netlify.app/",
        isMain: true,
    },
    {
        name: "Scheme Generator",
        desc: "A site assisting in crafting harmonious color palettes for UI designs, ensuring aesthetic cohesion and appeal.",        
        pic: "../images/projects/SchemeGenerator.png",
        link: "https://fascinating-pika-733774.netlify.app/",
        isMain: true,
    },
    {
        name: "Quizzical",
        desc: "A website where you can take quick quizzes on topics of your choice and instantly see your scores.",        
        pic: "../images/projects/Quizzical.png",
        link: "https://unique-otter-cdb693.netlify.app/",
        isMain: true,
    },
    {
        name: "Password Generator",
        desc: "Craft your own secure passwords with ease. Choose characters and length to fortify your digital defense.",
        pic: "../images/projects/PasswordGenerator.png",
        link: "https://comfy-moonbeam-971ac9.netlify.app/",
        isMain: true,
    },
    {
        name: "Restaurant App",
        desc: "A straightforward restaurant simulation website where you can place orders and complete payments.",        
        pic: "../images/projects/RestaurantApp.png",
        link: "https://bright-choux-47d4d4.netlify.app/",
        isMain: false,
    },
    {
        name: "Tenzies Game",
        desc: "\"Tenzies\" is a fast-paced dice game of luck and strategy. Roll the dice, match numbers, and race to victory!",        
        pic: "../images/projects/TenziesGame.png",
        link: "https://fascinating-bubblegum-5a1c44.netlify.app/",
        isMain: false,
    },
    {
        name: "Twimba",
        desc: "A streamlined take on Twitter (or X), where users can easily sign up, log in, tweet, and engage with others' tweets!",        
        pic: "../images/projects/Twimba.png",
        link: "https://friendly-crumble-840d4a.netlify.app/",
        isMain: false,
    },
    {
        name: "Learning Journal",
        desc: "A website dedicated to personal learning journals, where you can delve into a student's journey and explore their blogs.",        
        pic: "../images/projects/LearningJournal.png",
        link: "https://sweet-cactus-11e53c.netlify.app/",
        isMain: false,
    },
    {
        name: "Meme Generator",
        desc: "A site showcasing random memes sourced from an external API, and enabling users to add their own captions.",        
        pic: "../images/projects/MemeGenerator.png",
        link: "https://spectacular-croissant-c04e99.netlify.app/",
        isMain: false,
    },
    {
        name: "Oldagram",
        desc: "Imagine a revamped version of Instagram, where users can smoothly peruse posts and interact with them through linking.",
        pic: "../images/projects/Oldagram.png",
        link: "https://monumental-capybara-a894e7.netlify.app/",
        isMain: false,
    },
    {
        name: "Cat Meme Picker",
        desc: "Match your mood with purr-fect cat memes instantly. Express yourself with feline fun!",        
        pic: "../images/projects/CatMemePicker.png",
        link: "https://leafy-parfait-a8b887.netlify.app/",
        isMain: false,
    },

    {
        name: "NFT Site",
        desc: "A fully responsive website delving into the world of NFTs with a blend of sharp critique and humor.",        
        pic: "../images/projects/NFT-Site.png",
        link: "https://cheery-pithivier-3bd86d.netlify.app/",
        isMain: false,
    },
    {
        name: "Chef Job Registration",
        desc: "A chef job registration portal for Omar's restaurant, streamlining the process for applicants to sign up and apply.",        
        pic: "../images/projects/ChefJobRegistration.png",
        link: "https://gregarious-parfait-ca991a.netlify.app/",
        isMain: false,
    },
    {
        name: "Wizard Game",
        desc: "A whimsical game where you play as a wizard tasked with defeating three monsters to emerge victorious.",        
        pic: "../images/projects/WizardGame.png",
        link: "https://illustrious-monstera-19feae.netlify.app/",
        isMain: false,
    },
];
